"""Serializers que solo describen los bodies en el esquema OpenAPI.

Sin docstrings en las clases: drf-spectacular los publica como descripción
del componente, y lo que ve quien consume la API va en inglés.

Ninguna view los usa en runtime: las views de `apps.authentication` leen `request.data`
a mano y los services arman los dicts. Si cambia la forma de un dict en
`services/`, hay que cambiarla aquí también. Los errores genéricos,
`OkResponseSerializer` y `RoleSummarySerializer` son los de
`apps.authorization.docs.schemas`: un componente del esquema tiene una sola
clase.
"""
from rest_framework import serializers

from apps.authorization.docs.schemas import RoleSummarySerializer

# --- errores -------------------------------------------------------------------


class SessionUnauthorizedResponseSerializer(serializers.Serializer):
    error = serializers.CharField()
    csrfToken = serializers.CharField(help_text="CSRF token to send in `X-CSRFToken`.")


# --- sesión --------------------------------------------------------------------


class SessionUserSerializer(serializers.Serializer):
    id = serializers.CharField(help_text="User id (prefix `U`), generated by the server.")
    email = serializers.CharField(help_text="Always lowercase.")
    firstName = serializers.CharField()
    lastName = serializers.CharField()
    isStaff = serializers.BooleanField(help_text="`true` when the user is active and has a role.")
    role = RoleSummarySerializer(allow_null=True)
    permissions = serializers.ListField(
        child=serializers.CharField(),
        help_text="Permission codes granted by the role (`orders.view`); empty without a role.",
    )
    emailVerified = serializers.BooleanField()


class SessionPayloadSerializer(serializers.Serializer):
    authenticated = serializers.BooleanField()
    user = SessionUserSerializer()
    csrfToken = serializers.CharField(help_text="CSRF token to send in `X-CSRFToken`.")


class LoginRequestSerializer(serializers.Serializer):
    email = serializers.CharField(help_text="Trimmed and lowercased before the lookup.")
    password = serializers.CharField()


# --- enlaces por correo ----------------------------------------------------------


class PasswordResetRequestSerializer(serializers.Serializer):
    email = serializers.CharField(
        help_text="A missing or invalid email still returns the same 200 response."
    )


class PasswordResetRequestedResponseSerializer(serializers.Serializer):
    ok = serializers.BooleanField()
    message = serializers.CharField()


class PasswordResetConfirmRequestSerializer(serializers.Serializer):
    token = serializers.CharField(help_text="Token from the reset link.")
    password = serializers.CharField(help_text="Must pass `AUTH_PASSWORD_VALIDATORS`.")


class VerifyEmailResendResponseSerializer(serializers.Serializer):
    ok = serializers.BooleanField()
    emailVerified = serializers.BooleanField(
        help_text="`true` when the account was already verified and no email was sent."
    )

