# Generated by Django 5.2.17 on 2026-10-11 02:25

import django.db.models.deletion
import django.db.models.functions.datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("number", models.TextField(unique=True)),
                (
                    "status",
                    models.TextField(
                        choices=[
                            ("OPEN", "Open"),
                            ("PENDING_PAYMENT", "Pending Payment"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                            ("REJECTED", "Rejected"),
                        ],
                        db_default="OPEN",
                        default="OPEN",
                    ),
                ),
                (
                    "payment_status",
                    models.TextField(
                        choices=[
                            ("UNPAID", "Unpaid"),
                            ("PAID", "Paid"),
                            ("FAILED", "Failed"),
                            ("PARTIALLY_REFUNDED", "Partially Refunded"),
                            ("REFUNDED", "Refunded"),
                        ],
                        db_default="UNPAID",
                        default="UNPAID",
                    ),
                ),
                (
                    "fulfillment_status",
                    models.TextField(
                        choices=[
                            ("UNFULFILLED", "Unfulfilled"),
                            ("PREPARING", "Preparing"),
                            ("SHIPPED", "Shipped"),
                            ("DELIVERED", "Delivered"),
                        ],
                        db_default="UNFULFILLED",
                        default="UNFULFILLED",
                    ),
                ),
                (
                    "carrier",
                    models.TextField(
                        blank=True,
                        choices=[
                            ("UPS", "UPS"),
                            ("FEDEX", "FedEx"),
                            ("USPS", "USPS"),
                            ("OTHER", "Other"),
                        ],
                        db_default="",
                        default="",
                    ),
                ),
                ("tracking_number", models.TextField(blank=True, db_default="", default="")),
                ("shipped_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("data", models.JSONField(default=dict)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to="customers.customer",
                    ),
                ),
            ],
            options={
                "db_table": "orders",
                "permissions": [
                    ("change_status", "Can change order status"),
                    ("cancel_order", "Can cancel orders"),
                    ("manage_cores", "Can manage cores"),
                    ("manage_returns", "Can manage returns"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("provider", models.TextField()),
                ("provider_id", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.TextField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PAID", "Paid"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                            ("PARTIALLY_REFUNDED", "Partially Refunded"),
                            ("REFUNDED", "Refunded"),
                        ]
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(db_default=0, decimal_places=2, default=0, max_digits=12),
                ),
                ("data", models.JSONField(db_default={}, default=dict)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to="checkout.order",
                    ),
                ),
            ],
            options={
                "db_table": "payments",
                "permissions": [
                    ("take_payment", "Can take payments"),
                    ("refund_payment", "Can refund payments"),
                    ("view_transaction_id", "Can view payment transaction IDs"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Refund",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "status",
                    models.TextField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SUCCEEDED", "Succeeded"),
                            ("FAILED", "Failed"),
                            ("CANCELED", "Canceled"),
                        ],
                        db_default="PENDING",
                        default="PENDING",
                    ),
                ),
                ("reason", models.TextField(blank=True, db_default="", default="")),
                ("stripe_refund_id", models.TextField(blank=True, null=True, unique=True)),
                ("created_by", models.TextField()),
                ("data", models.JSONField(db_default={}, default=dict)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refunds",
                        to="checkout.payment",
                    ),
                ),
            ],
            options={
                "db_table": "refunds",
            },
        ),
    ]
