# Generated by Django 5.2.17 on 2026-09-27 11:18

import django.db.models.deletion
import django.db.models.functions.datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_db_on_delete'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.TextField(db_default='PENDING', default='PENDING')),
                ('reason', models.TextField(blank=True, db_default='', default='')),
                ('stripe_refund_id', models.TextField(blank=True, null=True, unique=True)),
                ('created_by', models.TextField()),
                ('data', models.JSONField(db_default={}, default=dict)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), default=django.utils.timezone.now)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='checkout.payment')),
            ],
            options={
                'db_table': 'refunds',
            },
        ),
    ]
