# Generated by Django 5.2.17 on 2026-09-27 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0008_payment_paid_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.TextField(choices=[('UNPAID', 'Unpaid'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('PARTIALLY_REFUNDED', 'Partially Refunded'), ('REFUNDED', 'Refunded')], db_default='UNPAID', default='UNPAID'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.TextField(choices=[('OPEN', 'Open'), ('PENDING_PAYMENT', 'Pending Payment'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('REJECTED', 'Rejected')], db_default='OPEN', default='OPEN'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.TextField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('PARTIALLY_REFUNDED', 'Partially Refunded'), ('REFUNDED', 'Refunded')]),
        ),
        migrations.AlterField(
            model_name='refund',
            name='status',
            field=models.TextField(choices=[('PENDING', 'Pending'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed'), ('CANCELED', 'Canceled')], db_default='PENDING', default='PENDING'),
        ),
    ]
