# Generated by Django 5.2.17 on 2026-09-27 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0009_status_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='carrier',
            field=models.TextField(blank=True, choices=[('UPS', 'UPS'), ('FEDEX', 'FedEx'), ('USPS', 'USPS'), ('OTHER', 'Other')], db_default='', default=''),
        ),
        migrations.AddField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='fulfillment_status',
            field=models.TextField(choices=[('UNFULFILLED', 'Unfulfilled'), ('PREPARING', 'Preparing'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered')], db_default='UNFULFILLED', default='UNFULFILLED'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.TextField(blank=True, db_default='', default=''),
        ),
    ]
