# Generated by Django 5.2.17 on 2026-10-11 02:25

import django.db.models.deletion
import django.db.models.functions.datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("email", models.TextField(blank=True, null=True)),
                ("data", models.JSONField(default=dict)),
                (
                    "tax_status",
                    models.TextField(
                        choices=[
                            ("VERIFIED", "Verified"),
                            ("REJECTED", "Rejected"),
                            ("EXPIRED", "Expired"),
                            ("PENDING VERIFICATION", "Pending Verification"),
                            ("NOT SUBMITTED", "Not Submitted"),
                        ],
                        db_default="NOT SUBMITTED",
                        default="NOT SUBMITTED",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                (
                    "updated_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="customer",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "customers",
                "permissions": [("review_tax_exemption", "Can review tax exemptions")],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("user__isnull", True)),
                        fields=("email",),
                        name="customers_guest_email_unique",
                    )
                ],
            },
        ),
    ]
