# Generated by Django 5.2.17 on 2026-09-23 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_managed_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='activation_expires_at',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='activation_token_hash',
        ),
    ]
