# Generated by Django 5.2.17 on 2026-09-27 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_db_on_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='tax_status',
            field=models.TextField(choices=[('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired'), ('PENDING VERIFICATION', 'Pending Verification'), ('NOT SUBMITTED', 'Not Submitted')], db_default='NOT SUBMITTED', default='NOT SUBMITTED'),
        ),
    ]
