# Generated by Django 5.1.15 on 2026-09-23 14:01

import django.db.models.deletion
import django.db.models.functions.datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tt_auth', '0008_drop_legacy_sessions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AccountToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.TextField(choices=[('password_reset', 'Password reset'), ('email_verification', 'Email verification')])),
                ('token_hash', models.TextField(unique=True)),
                ('email', models.TextField()),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_tokens', to='tt_auth.user')),
            ],
            options={
                'db_table': 'account_tokens',
                'default_permissions': (),
                'indexes': [models.Index(fields=['user', 'purpose'], name='account_tokens_user_purpose')],
            },
        ),
    ]
