# Generated by Django 5.2.17 on 2026-09-23 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tt_auth', '0011_move_backoffice_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounttoken',
            name='purpose',
            field=models.TextField(choices=[('password_reset', 'Password reset'), ('email_verification', 'Email verification'), ('activation', 'Portal activation')]),
        ),
        migrations.AlterField(
            model_name='accounttoken',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_tokens', to='tt_auth.user'),
        ),
        migrations.AddConstraint(
            model_name='accounttoken',
            constraint=models.CheckConstraint(condition=models.Q(('user__isnull', False), ('purpose', 'activation'), _connector='OR'), name='account_tokens_user_required'),
        ),
    ]
