# Generated by Django 5.2.17 on 2026-10-11 02:25

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DocumentSequence",
            fields=[
                ("key", models.TextField(primary_key=True, serialize=False)),
                ("last_value", models.PositiveBigIntegerField()),
            ],
            options={
                "db_table": "document_sequences",
                "default_permissions": (),
            },
        ),
    ]
