# Generated by Django 5.2.17 on 2026-10-11 02:25

import django.db.models.deletion
import django.db.models.functions.datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Quote",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("number", models.TextField(unique=True)),
                (
                    "status",
                    models.TextField(
                        choices=[
                            ("BUILDING", "Building"),
                            ("ACTIVE", "Active"),
                            ("CONTACTED", "Contacted"),
                            ("EXPIRED", "Expired"),
                            ("CONVERTED", "Converted"),
                            ("LOST", "Lost"),
                        ],
                        db_default="BUILDING",
                        default="BUILDING",
                    ),
                ),
                ("data", models.JSONField(default=dict)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                    ),
                ),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "updated_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quotes",
                        to="customers.customer",
                    ),
                ),
            ],
            options={
                "db_table": "quotes",
                "permissions": [
                    ("send_quote", "Can send quotes"),
                    ("convert_quote", "Can convert quotes"),
                ],
            },
        ),
    ]
