# Generated by Django 5.2.17 on 2026-09-27 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0004_db_on_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='status',
            field=models.TextField(choices=[('BUILDING', 'Building'), ('ACTIVE', 'Active'), ('CONTACTED', 'Contacted'), ('EXPIRED', 'Expired'), ('CONVERTED', 'Converted'), ('LOST', 'Lost')], db_default='BUILDING', default='BUILDING'),
        ),
    ]
