# Generated by Django 5.2.17 on 2026-10-11 02:25

import django.db.models.functions.datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("actor_id", models.TextField(blank=True, null=True)),
                ("action", models.TextField()),
                ("entity_type", models.TextField(blank=True, null=True)),
                ("entity_id", models.TextField(blank=True, null=True)),
                ("data", models.JSONField(db_default={}, default=dict)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                    ),
                ),
            ],
            options={
                "db_table": "activity_logs",
            },
        ),
    ]
