# Generated by Django 5.2.17 on 2026-10-11 02:25

import django.contrib.postgres.indexes
import django.db.models.deletion
import django.db.models.functions.datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("code", models.CharField(max_length=120, unique=True)),
                ("data", models.JSONField(default=dict)),
            ],
            options={
                "db_table": "applications",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("slug", models.SlugField(max_length=120, unique=True)),
                ("data", models.JSONField(default=dict)),
                ("active", models.BooleanField(db_default=True, default=True)),
                (
                    "updated_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                    ),
                ),
            ],
            options={
                "db_table": "products",
                "permissions": [
                    ("edit_pricing", "Can edit pricing"),
                    ("view_costs", "Can view costs"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ProductFitment",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fitments",
                        to="catalog.application",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fitments",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "db_table": "product_fitments",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="applications",
            field=models.ManyToManyField(
                blank=True,
                related_name="products",
                through="catalog.ProductFitment",
                to="catalog.application",
            ),
        ),
        migrations.AddConstraint(
            model_name="productfitment",
            constraint=models.UniqueConstraint(
                fields=("product", "application"), name="product_fitments_unique"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["data"], name="idx_products_data"
            ),
        ),
    ]
