"""Serializers que solo describen los bodies en el esquema OpenAPI.

Sin docstrings en las clases: drf-spectacular los publica como descripción
del componente, y lo que ve quien consume la API va en inglés.

Ninguna view los usa en runtime: las views de `apps.authorization` leen
`request.data` a mano y `services/` arma los dicts. Si cambia la forma
de un dict en `services/`, hay que cambiarla aquí también. Los errores,
`OkResponseSerializer` y `RoleSummarySerializer` los reutiliza
`apps.authentication.docs.schemas` para la sesión y el login.
"""
from drf_spectacular.utils import PolymorphicProxySerializer
from rest_framework import serializers

# --- errores -------------------------------------------------------------------


class ErrorResponseSerializer(serializers.Serializer):
    error = serializers.CharField(help_text="Literal English error message.")


# Forma de los errores que genera DRF por su cuenta (CSRF, throttle, JSON mal
# formado): no hay `EXCEPTION_HANDLER`, así que usan `detail`. Va en comentario y
# no en docstring porque drf-spectacular publica el docstring como descripción.
class DetailResponseSerializer(serializers.Serializer):
    detail = serializers.CharField(help_text="Error message generated by Django REST framework.")


# Mismo código de estado, dos formas posibles según quién genera el error.
ErrorOrDetailResponse = PolymorphicProxySerializer(
    component_name="ErrorOrDetailResponse",
    serializers=[ErrorResponseSerializer, DetailResponseSerializer],
    resource_type_field_name=None,
)


class OkResponseSerializer(serializers.Serializer):
    ok = serializers.BooleanField()


# --- roles y usuarios del panel --------------------------------------------------


class RoleSummarySerializer(serializers.Serializer):
    slug = serializers.CharField()
    name = serializers.CharField()
    fullAccess = serializers.BooleanField()


class AdminRoleSerializer(serializers.Serializer):
    id = serializers.IntegerField()
    slug = serializers.CharField()
    name = serializers.CharField()
    fullAccess = serializers.BooleanField()


class AdminUserSerializer(serializers.Serializer):
    id = serializers.CharField()
    email = serializers.CharField()
    firstName = serializers.CharField()
    lastName = serializers.CharField()
    name = serializers.CharField(help_text="First and last name; the email when both are empty.")
    active = serializers.BooleanField()
    isStaff = serializers.BooleanField(help_text="`true` when the user is active and has a role.")
    role = RoleSummarySerializer(allow_null=True)
    permissions = serializers.ListField(child=serializers.CharField())
    createdAt = serializers.DateTimeField()


class AdminUserResultSerializer(serializers.Serializer):
    ok = serializers.BooleanField()
    user = AdminUserSerializer()


# Pese al `PUT`, los dos campos son opcionales: el service solo toca los que
# llegan. Cualquier otro campo (email, contraseña, nombres) es un 400: la
# cuenta es de su dueño y el panel solo decide su acceso.
class AdminUserUpdateRequestSerializer(serializers.Serializer):
    role = serializers.CharField(
        required=False,
        allow_null=True,
        help_text="Slug of an existing role; `null` removes the role and panel access.",
    )
    active = serializers.BooleanField(required=False, help_text="Must be a JSON boolean.")
