# Generated by Django 5.2.17 on 2026-10-11 02:25

import django.db.models.functions.datetime
import django.utils.timezone
from django.db import migrations, models

import apps.authentication.models.user


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(blank=True, null=True, verbose_name="last login"),
                ),
                (
                    "id",
                    models.TextField(
                        default=apps.authentication.models.user.new_user_id,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.TextField(unique=True)),
                ("active", models.BooleanField(default=True)),
                ("first_name", models.TextField(blank=True, null=True)),
                ("last_name", models.TextField(blank=True, null=True)),
                ("display_name", models.TextField(blank=True, null=True)),
                ("email_verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                    ),
                ),
            ],
            options={
                "db_table": "users",
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="AccountToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "purpose",
                    models.TextField(
                        choices=[
                            ("password_reset", "Password reset"),
                            ("email_verification", "Email verification"),
                            ("activation", "Portal activation"),
                        ]
                    ),
                ),
                ("token_hash", models.TextField(unique=True)),
                ("email", models.TextField()),
                ("expires_at", models.DateTimeField()),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                    ),
                ),
            ],
            options={
                "db_table": "account_tokens",
                "default_permissions": (),
            },
        ),
    ]
