# Generated by Django 5.2.17 on 2026-10-11 02:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("authentication", "0001_initial"),
        ("authorization", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="users",
                to="authorization.role",
            ),
        ),
        migrations.AddField(
            model_name="accounttoken",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="account_tokens",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="accounttoken",
            index=models.Index(fields=["user", "purpose"], name="account_tokens_user_purpose"),
        ),
        migrations.AddConstraint(
            model_name="accounttoken",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("user__isnull", False), ("purpose", "activation"), _connector="OR"
                ),
                name="account_tokens_user_required",
            ),
        ),
    ]
